{% set name = "mobie" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d4f6d822295a2f69cb3cddf909fa53a60c49ab89b43e8c2768eb13d5b106772

build:
  noarch: python
  number: 1
  entry_points:
    - mobie=mobie:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jgo >=0.4.0
    - pip
    - python {{ python_min }}
  run:
    - jgo >=0.4.0
    - python >={{ python_min }}
    - openjdk =8
    - maven
    - blosc

test:
  requires:
    - python {{ python_min }}
  imports:
    - mobie
  commands:
    # all should show help message
    - mobie project
    - mobie files
    - mobie table
    - mobie hcs

about:
  home: https://github.com/mobie/mobie-cmd
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Viewer for big multi-modal image data

extra:
  recipe-maintainers:
    - tischi
